import pytest
from unittest.mock import AsyncMock, MagicMock, patch
from back.services.logic_oracle_service import LogicOracleService
from back.models.api.game import PlayerInput, TimelineEvent
from back.models.enums import TimelineEventType

@pytest.fixture
def mock_session_service():
    return AsyncMock()

@pytest.mark.asyncio
async def test_resolve_turn_delegates_to_graph(mock_session_service):
    """
    Test that resolve_turn initializes the graph and invokes it.
    """
    with patch("back.services.logic_oracle_service.build_game_graph", new_callable=AsyncMock) as mock_build:
        # Create a mock app returned by build_game_graph
        mock_app = AsyncMock()
        mock_build.return_value = mock_app
        
        # Setup initial state (aget_state)
        mock_app.aget_state.return_value = MagicMock(values={"ui_messages": []})
        
        # Setup final state (ainvoke result)
        # Simulate some logs generated by the graph
        log_event = TimelineEvent(
            type=TimelineEventType.NARRATIVE,
            timestamp="2024-01-01", 
            content="Hero attacks!",
            icon="sword"
        )
        mock_app.ainvoke.return_value = {
            "ui_messages": [log_event],
            "messages": []
        }
        
        service = LogicOracleService()
        
        input_data = PlayerInput(input_mode="text", text_content="Attack")
        
        # Execute
        result = await service.resolve_turn("session-1", input_data, mock_session_service, None)
        
        # Verify Graph Build
        mock_build.assert_awaited_once()
        assert service.app == mock_app
        
        # Verify Graph Invocation
        mock_app.ainvoke.assert_awaited_once()
        call_args = mock_app.ainvoke.await_args
        assert call_args[0][0]["messages"][0].content == "Attack"
        
        # Verify Result Extraction
        assert len(result.logs) == 1
        assert result.narrative_context == "Hero attacks!"

@pytest.mark.asyncio
async def test_resolve_turn_calculates_delta(mock_session_service):
    """
    Test that logic oracle returns only NEW messages.
    """
    with patch("back.services.logic_oracle_service.build_game_graph", new_callable=AsyncMock) as mock_build:
        mock_app = AsyncMock()
        mock_build.return_value = mock_app
        
        # Initial state has 2 messages
        existing_logs = [
            TimelineEvent(type=TimelineEventType.SYSTEM_LOG, timestamp="t1", content="Old 1"),
            TimelineEvent(type=TimelineEventType.SYSTEM_LOG, timestamp="t2", content="Old 2")
        ]
        mock_app.aget_state.return_value = MagicMock(values={"ui_messages": existing_logs})
        
        # Final state has 3 messages (1 new)
        new_log = TimelineEvent(type=TimelineEventType.NARRATIVE, timestamp="t3", content="New Thing")
        mock_app.ainvoke.return_value = {
            "ui_messages": existing_logs + [new_log]
        }
        
        service = LogicOracleService()
        input_data = PlayerInput(input_mode="text", text_content="Go")
        
        result = await service.resolve_turn("session-1", input_data, mock_session_service, None)
        
        # Should only return the new log
        assert len(result.logs) == 1
        assert result.logs[0].content == "New Thing"
